apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aks
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: aks/crossplane
    repoURL: 'https://github.com/huynhduc0'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
