apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: eks/crossplane
    repoURL: 'https://github.com/huynhduc0'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
