apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: vn-crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider
  forProvider:
    resourceGroupNameRef:
      name: crossplane-rg-aks
    location: Central US
    addressSpace:
      - 10.2.0.0/16