apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: '1.14.5'
    chart: crossplane
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true