apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster/charts/crossplane/
    repoURL: 'https://github.com/crossplane/crossplane'
    targetRevision: v1.15.2
  sources: []
  project: default