apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{.Values.provider.name}}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  projectID: hihi-1541495393612
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: {{.Values.provider.name}}
      key: creds