apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{.Values.provider.name}}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  projectID: arcane-geode-422508-p4
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds