apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: {{ .Values.network.vpc.name }}
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    autoCreateSubnetworks: false
    routingMode: GLOBAL