apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: dev-private
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    networkRef:
      name: {{ .Values.network.vpc.name }}
    ipCidrRange: 10.0.0.0/18
    networkSelector:
    region: {{ .Values.zone }}
    secondaryIpRange:
      - ipCidrRange: 10.48.0.0/24
        rangeName: k8s-pod-range