apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name:  dev-private
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    ipCidrRange: 10.0.0.0/18
    networkSelector:
    region: us-central1
    secondaryIpRange:
      - ipCidrRange: 10.48.0.1/24
        rangeName: k8s-pod-range