apiVersion: compute.gcp.upbound.io/v1beta1
kind: Address
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    nat.name: "{{ .Values.network.vpc.name }}-ip"
  name: "{{ .Values.network.vpc.name }}-ip"
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    networkRef:
      name: "{{ .Values.network.vpc.name }}-private"
    addressType: EXTERNAL
    region: {{ .Values.zone }}