apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterNAT
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: dev-nat
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    logConfig:
      - enable: true
        filter: ERRORS_ONLY
    natIpAllocateOption: AUTO_ONLY
    region: us-central1
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
    subnetwork:
      - nameRef: dev-private