apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "5"
        argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "{{ .Values.network.vpc.name }}-forwarding-rule-ilb"
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    allow:
      - ports:
          - "80"
          - "443"
          - "8080"
        protocol: tcp
    direction: INGRESS
    networkRef:
      name: {{ .Values.network.vpc.name }}
    sourceRanges:
      - 10.0.0.0/24
    targetTags:
      - http-server