apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "{{ .Values.network.vpc.name }}-cluster"
spec:
  providerConfigRef:
    name: gpc-provider
  forProvider:
    initialNodeCount: 1
    nodeConfig:
      - machineType: e2-micro
        diskSizeGb: 10
    location: {{ .Values.zone }}
    networkRef:
      name: {{ .Values.network.vpc.name }}
    subnetworkRef:
      name: {{ .Values.network.vpc.name }}-private