apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "{{ .Values.network.vpc.name }}-cluster"
spec:
  providerConfigRef:
    name: {{ .Values.provider.name }}
  forProvider:
    location: {{ .Values.zone }}
    initialNodeCount: 1
    nodeConfig:
      machineType: f1-micro
    networkRef:
      name: {{ .Values.network.vpc.name }}
    subnetworkRef:
      name: {{ .Values.network.vpc.name }}-private
    ipAllocationPolicy:
      useIpAliases: true
