apiVersion: kubernetes.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: yc-provider
  forProvider:
    name: {{ .Values.cluster.name }}
    description: {{ .Values.cluster.name }}-cluster
    networkIdRef:
      name: {{ .Values.vpc.name }}
    serviceAccountId: ajeo0isdo22o053df63i
    nodeServiceAccountId: ajeo0isdo22o053df63i
    master:
      - version: "1.21"
        zonal:
          - zone:  {{ .Values.zone }}
            subnetIdRef:
              name: {{ .Values.vpc.subnet.name }}
        publicIp: false
    folderId: {{ .Values.folderId }}