apiVersion: kubernetes.yandex-cloud.upjet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: yc-provider
  forProvider:
    name: {{ .Values.cluster.name }}
    description: {{ .Values.cluster.name }}-cluster
    networkIdRef:
      name: {{ .Values.vpc.name }}
    serviceAccountId: ajerlcjs78pk72f0u4i4
    nodeServiceAccountId: ajerlcjs78pk72f0u4i4
    master:
      - version: "1.21"
        zonal:
          - zone:  {{ .Values.zone }}
            subnetIdRef:
              name: example-subnet-a
        publicIp: false
        maintenancePolicy:
          - autoUpgrade: false
            maintenanceWindow:
              - startTime: "15:00"
                duration: "3h"
    folderId: {{ .Values.folderId }}